export const cards = [
	{
		imageUrl: '/img/coffe1.png',
		title: 'Чашка кофе',
		description: 'Очень вкусная чашка кофе',
		price: 100,
	},
	{
		imageUrl: '/img/coffe2.png',
		title: 'Чашка кофе',
		description: 'Очень очень вкусная чашка кофе',
		price: 200,
	},
	{
		imageUrl: '/img/coffe1.png',
		title: 'Чашка кофе',
		description: 'Очень очень очень вкусная чашка кофе',
		price: 300,
	},
	{
		imageUrl: '/img/coffe2.png',
		title: 'Чашка кофе',
		description: 'Очень очень очень очень вкусная чашка кофе',
		price: 400,
	},
	{
		imageUrl: '/img/coffe1.png',
		title: 'Чашка кофе',
		description: 'Очень очень очень очень очень вкусная чашка кофе',
		price: 500,
	},
	{
		imageUrl: '/img/coffe2.png',
		title: 'Чашка кофе',
		description: 'Очень очень очень очень очень очень вкусная чашка кофе',
		price: 600,
	},
	{
		imageUrl: '/img/coffe1.png',
		title: 'Чашка кофе',
		description: 'Очень очень очень очень очень очень очень вкусная чашка кофе',
		price: 700,
	},
	{
		imageUrl: '/img/coffe2.png',
		title: 'Чашка кофе',
		description: 'Очень очень очень очень очень очень очень очень вкусная чашка кофе',
		price: 800,
	},
	{
		imageUrl: '/img/coffe1.png',
		title: 'Чашка кофе',
		description: 'Очень очень очень очень очень очень очень очень очень вкусная чашка кофе',
		price: 900,
	},
	{
		imageUrl: '/img/coffe2.png',
		title: 'Чашка кофе',
		description: 'Очень очень очень очень очень очень очень очень очень вкусная чашка кофе',
		price: 1000,
	},
	{
		imageUrl: '/img/coffe1.png',
		title: 'Чашка кофе',
		description: 'Очень очень очень очень очень очень очень очень очень вкусная чашка кофе',
		price: 1100,
	},
	{
		imageUrl: '/img/coffe2.png',
		title: 'Чашка кофе',
		description: 'Очень очень очень очень очень очень очень очень очень вкусная чашка кофе',
		price: 1200,
	},
	{
		imageUrl: '/img/coffe1.png',
		title: 'Чашка кофе',
		description: 'Очень очень очень очень очень очень очень очень очень вкусная чашка кофе',
		price: 1300,
	},
	{
		imageUrl: '/img/coffe2.png',
		title: 'Чашка кофе',
		description: 'Очень очень очень очень очень очень очень очень очень вкусная чашка кофе',
		price: 1400,
	},
	{
		imageUrl: '/img/coffe1.png',
		title: 'Чашка кофе',
		description: 'Очень очень очень очень очень очень очень очень очень вкусная чашка кофе',
		price: 1500,
	},
	{
		imageUrl: '/img/coffe2.png',
		title: 'Чашка кофе',
		description: 'Очень очень очень очень очень очень очень очень очень вкусная чашка кофе',
		price: 1600,
	},
];